spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: "http://127.0.0.1:8282"
          jwk-set-uri: "http://127.0.0.1:9000/oauth2/jwks"


server:
  port: 8072

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://127.0.0.1:8070/eureka/"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true