spring:
  application:
    name: products
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Allah@2551995
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8090
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://127.0.0.1:8070/eureka/"

